// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sinistros.Infrastructure.Persistence;

#nullable disable

namespace Sinistros.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sinistros.Domain.Apolices.Apolice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Ramo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ramo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_apolices");

                    b.ToTable("Apolices");
                });

            modelBuilder.Entity("Sinistros.Domain.Clientes.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Sinistros.Domain.Sinistros.HistoricoSinistro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo");

                    b.Property<Guid>("SinistroId")
                        .HasColumnType("uuid")
                        .HasColumnName("sinistro_id");

                    b.Property<string>("StatusAnterior")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_anterior");

                    b.Property<string>("StatusNovo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_novo");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario");

                    b.HasKey("Id")
                        .HasName("pk_historico_sinistros");

                    b.HasIndex("SinistroId")
                        .HasDatabaseName("ix_historico_sinistros_sinistro_id");

                    b.ToTable("HistoricoSinistros", (string)null);
                });

            modelBuilder.Entity("Sinistros.Domain.Sinistros.Sinistro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApoliceId")
                        .HasColumnType("uuid")
                        .HasColumnName("apolice_id");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_abertura");

                    b.Property<DateTime?>("DataEncerramento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_encerramento");

                    b.Property<DateTime>("DataOcorrencia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_ocorrencia");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_sinistros");

                    b.ToTable("Sinistros");
                });

            modelBuilder.Entity("Sinistros.Domain.Apolices.Apolice", b =>
                {
                    b.OwnsOne("Sinistros.Domain.Apolices.NumeroApolice", "Numero", b1 =>
                        {
                            b1.Property<Guid>("ApoliceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("valor");

                            b1.HasKey("ApoliceId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("Apolices");

                            b1.WithOwner()
                                .HasForeignKey("ApoliceId");
                        });

                    b.OwnsOne("Sinistros.Domain.Apolices.PeriodoVigencia", "Vigencia", b1 =>
                        {
                            b1.Property<Guid>("ApoliceId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("Fim")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("fim");

                            b1.Property<DateTime>("Inicio")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("inicio");

                            b1.HasKey("ApoliceId");

                            b1.ToTable("Apolices");

                            b1.WithOwner()
                                .HasForeignKey("ApoliceId");
                        });

                    b.Navigation("Numero")
                        .IsRequired();

                    b.Navigation("Vigencia")
                        .IsRequired();
                });

            modelBuilder.Entity("Sinistros.Domain.Clientes.Cliente", b =>
                {
                    b.OwnsOne("Sinistros.Domain.Clientes.Documento", "Documento", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("numero");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Documento")
                        .IsRequired();
                });

            modelBuilder.Entity("Sinistros.Domain.Sinistros.HistoricoSinistro", b =>
                {
                    b.HasOne("Sinistros.Domain.Sinistros.Sinistro", null)
                        .WithMany("HistoricoSinistros")
                        .HasForeignKey("SinistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_historico_sinistros_sinistros_sinistro_id");
                });

            modelBuilder.Entity("Sinistros.Domain.Sinistros.Sinistro", b =>
                {
                    b.OwnsOne("Sinistros.Domain.Sinistros.MotivoNegativa", "Motivo", b1 =>
                        {
                            b1.Property<Guid>("SinistroId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Texto")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("motivo_negativa_texto");

                            b1.HasKey("SinistroId");

                            b1.ToTable("Sinistros");

                            b1.WithOwner()
                                .HasForeignKey("SinistroId");
                        });

                    b.OwnsOne("Sinistros.Domain.SeedWork.Dinheiro", "ValorAprovado", b1 =>
                        {
                            b1.Property<Guid>("SinistroId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Moeda")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("valor_aprovado_moeda");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("valor_aprovado_quantia");

                            b1.HasKey("SinistroId");

                            b1.ToTable("Sinistros");

                            b1.WithOwner()
                                .HasForeignKey("SinistroId");
                        });

                    b.OwnsOne("Sinistros.Domain.SeedWork.Dinheiro", "ValorEstimado", b1 =>
                        {
                            b1.Property<Guid>("SinistroId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Moeda")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("valor_estimado_moeda");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("valor_estimado_quantia");

                            b1.HasKey("SinistroId");

                            b1.ToTable("Sinistros");

                            b1.WithOwner()
                                .HasForeignKey("SinistroId");
                        });

                    b.Navigation("Motivo");

                    b.Navigation("ValorAprovado");

                    b.Navigation("ValorEstimado")
                        .IsRequired();
                });

            modelBuilder.Entity("Sinistros.Domain.Sinistros.Sinistro", b =>
                {
                    b.Navigation("HistoricoSinistros");
                });
#pragma warning restore 612, 618
        }
    }
}
